#!/usr/bin/env python3
"""
Generate computed-goto threaded dispatch tables from m68kops.c.

Reads the existing m68ki_instruction_jump_table initializer and produces:
  - m68kops_threaded_table.inc:  65536-entry table of label addresses
  - m68kops_threaded_labels.inc: one label per unique handler that calls the
                                  handler function and gotos dispatch_next

These files are #included inside m68k_execute_threaded() in m68kops.c.
"""
import re
import sys
import os


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src = os.path.join(here, 'm68kops.c')
    with open(src, 'r') as f:
        content = f.read()

    # Find the jump table initializer block.
    m = re.search(
        r'm68ki_instruction_jump_table\[0x10000\]\)\(void\)\s*=\s*\{(.*?)\};',
        content, re.DOTALL)
    if not m:
        print("ERROR: could not locate m68ki_instruction_jump_table initializer",
              file=sys.stderr)
        return 1

    raw = m.group(1)
    entries = [tok.strip() for tok in raw.split(',')]
    entries = [e for e in entries if e]
    if len(entries) != 0x10000:
        print(f"ERROR: expected 65536 entries, got {len(entries)}",
              file=sys.stderr)
        return 1

    unique = sorted(set(entries))
    print(f"Parsed {len(entries)} opcodes, {len(unique)} unique handlers",
          file=sys.stderr)

    # Label-address table: one 64-bit (or 32-bit) pointer per opcode.
    table_path = os.path.join(here, 'm68kops_threaded_table.inc')
    with open(table_path, 'w') as f:
        f.write('/* Auto-generated by gen_threaded.py - do not edit. */\n')
        for i in range(0, 0x10000, 8):
            row = ', '.join(f'&&l_{e}' for e in entries[i:i + 8])
            f.write(f'    {row},\n')

    # Labels: each unique handler becomes a label that calls the function and
    # jumps back to dispatch_next.
    labels_path = os.path.join(here, 'm68kops_threaded_labels.inc')
    with open(labels_path, 'w') as f:
        f.write('/* Auto-generated by gen_threaded.py - do not edit. */\n')
        for name in unique:
            f.write(f'l_{name}: {name}(); goto dispatch_next;\n')

    print(f"Wrote {table_path}", file=sys.stderr)
    print(f"Wrote {labels_path}", file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
