#!/usr/bin/env python3
"""
Transform Musashi's m68kops.c handler functions into labeled blocks
for computed goto (threaded) dispatch.

Generates two files:
  m68k_handlers.inc  - All handler code as labeled blocks
  m68k_goto_table.inc - The 65536-entry goto table initializer

Each handler function:
    static void m68k_op_xxx(void) { ... return; ... }
becomes:
    m68k_op_xxx: { ... goto dispatch_next; ... goto dispatch_next; }
"""

import re
import sys

def extract_handlers(content):
    """Extract handler functions from m68kops.c as (name, body) pairs."""
    # Match: static void m68k_op_XXX(void)\n{\n...\n}\n
    pattern = r'static void (m68k_op_\w+)\(void\)\n\{(.*?)\n\}'
    handlers = []
    for m in re.finditer(pattern, content, re.DOTALL):
        name = m.group(1)
        body = m.group(2)
        handlers.append((name, body))
    return handlers


def transform_handler(name, body):
    """Convert a handler function body to a labeled block.
    - Replace bare 'return;' with 'goto dispatch_next;'
    - Add 'goto dispatch_next;' at the end if not already there
    """
    # Replace return; with goto dispatch_next;
    # Only replace bare returns (not 'return value;')
    transformed = re.sub(r'\breturn\s*;', 'goto dispatch_next;', body)

    # Check if the last statement is already a goto
    stripped = transformed.rstrip()
    if not stripped.endswith('goto dispatch_next;') and not stripped.endswith('}'):
        transformed += '\n\tgoto dispatch_next;'
    elif stripped.endswith('}'):
        # The body ends with a closing brace (e.g., if/else block)
        # Add goto after it
        transformed += '\n\tgoto dispatch_next;'

    return f'{name}: {{{transformed}\n}}\n'


def extract_jump_table(content):
    """Extract the pre-generated jump table entries."""
    m = re.search(
        r'void \(\*m68ki_instruction_jump_table\[0x10000\]\)\(void\) = \{(.*?)\};',
        content, re.DOTALL)
    if not m:
        print("ERROR: Jump table not found", file=sys.stderr)
        sys.exit(1)

    table_text = m.group(1)
    entries = [e.strip().rstrip(',') for e in table_text.split(',') if e.strip()]
    if len(entries) != 65536:
        print(f"WARNING: Expected 65536 entries, got {len(entries)}", file=sys.stderr)
    return entries


def main():
    with open('m68kops.c') as f:
        content = f.read()

    # Extract handlers
    handlers = extract_handlers(content)
    handler_names = set(name for name, _ in handlers)
    print(f"Extracted {len(handlers)} handler functions", file=sys.stderr)

    # Extract jump table
    jump_table = extract_jump_table(content)

    # Generate handlers include file
    with open('m68k_handlers.inc', 'w') as f:
        f.write("/* Auto-generated: handler labeled blocks for computed goto dispatch */\n")
        f.write("/* Do not edit - generated by gen_threaded.py */\n\n")

        for name, body in handlers:
            f.write(transform_handler(name, body))
            f.write('\n')

    print(f"Written m68k_handlers.inc", file=sys.stderr)

    # Generate goto table include file
    with open('m68k_goto_table.inc', 'w') as f:
        f.write("/* Auto-generated: computed goto dispatch table */\n")
        f.write("/* Do not edit - generated by gen_threaded.py */\n\n")
        f.write("static void *m68k_goto_table[0x10000] = {\n")

        for i, entry in enumerate(jump_table):
            if i % 8 == 0:
                f.write("    ")
            f.write(f"&&{entry}, ")
            if i % 8 == 7:
                f.write("\n")

        f.write("\n};\n")

    print(f"Written m68k_goto_table.inc", file=sys.stderr)


if __name__ == '__main__':
    main()
