ifndef BIOS
$(error NeoGeo BIOS not specified: use make mvs64 BIOS=<bios.bin>)
endif
ifndef ROM
$(error NeoGeo game ROM not specified: use make mvs64 ROM=<rom.zip>)
endif

BUILD_DIR = build/mvs64

include $(N64_INST)/include/n64.mk

# 68K CPU core selection: USE_FAME=1 for FAME, otherwise Musashi
ifdef USE_FAME
src_68k = cpu/fame/famec.c fame_adapter.c
CFLAGS += -DUSE_FAME -I.
# FAME is enormous; needs reduced optimization to avoid GCC memory issues
$(BUILD_DIR)/cpu/fame/famec.o: CFLAGS += -g0 -O2 -fno-expensive-optimizations
else
src_68k = m68kcpu.c m68kops.c
# Musashi's generated opcode file is huge; keep at -O2
$(BUILD_DIR)/m68kops.o: CFLAGS += -O2
endif

src = emu.c roms.c hw.c video.c platform_n64.c sprite_cache.c lib/rdl.c m64k/tlb.c $(src_68k) $(wildcard hle_*.c)
rsp = rsp_video.S
asm =
obj = $(src:%.c=$(BUILD_DIR)/%.o) $(asm:%.S=$(BUILD_DIR)/%.o) $(rsp:%.S=$(BUILD_DIR)/%.o)

src_makerom = mvsmakerom.c miniz.c
obj_makerom = $(src_makerom:%.c=$(BUILD_DIR)/%.o)

CFLAGS += -Wno-unused-function -O3 -flto -fomit-frame-pointer -finline-limit=300 -funroll-loops
# Uncomment to enable TLB-mapped instruction fetch (requires TLB miss handler)
# CFLAGS += -DUSE_TLB_FETCH
LDFLAGS += -flto

ROMNAME=$(notdir $(basename $(ROM)))
ROMDIR=$(ROM:%.zip=%.n64)

all: mvsmakerom mvs64-${ROMNAME}.z64

test:
	make -f Makefile.tests all

$(BUILD_DIR)/mvs64-${ROMNAME}.dfs: $(ROM) mvsmakerom
	@echo "    [MVS] ${ROMDIR}"
	./mvsmakerom $(BIOS) $(ROM)
	@echo "    [DFS] $@"
	$(N64_MKDFS) $@ $(ROMDIR) >/dev/null

mvs64-${ROMNAME}.z64: $(BUILD_DIR)/mvs64-${ROMNAME}.dfs
mvs64-${ROMNAME}.z64: N64_ROM_TITLE="MVS64: ${ROMNAME}"
$(BUILD_DIR)/mvs64-${ROMNAME}.elf: $(obj)

mvsmakerom: $(obj_makerom)
	@echo "    [LD] $@"
	$(CC) $(LDFLAGS) -o $@ $^

clean:
	rm -f $(obj)
	rm -f $(obj_makerom)
	rm -f $(asm:%.S=$(BUILD_DIR)/%.o)
	rm -f $(rsp:%.S=$(BUILD_DIR)/%.rsp)
	rm -f $(src:%.c=$(BUILD_DIR)/%.d) $(asm:%.S=$(BUILD_DIR)/%.d)
	rm -f mvs64-*.elf
	rm -f mvs64-*.dfs
	rm -f mvs64-*.z64

-include $(src:%.c=$(BUILD_DIR)/%.d) $(asm:%.S=$(BUILD_DIR)/%.d) $(src_makerom:%.c=$(BUILD_DIR)/%.d)

.PHONY: clean test
